### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by csantos1113** [iamyoki/transition-hook#15]
Hi @iamyoki - thanks for your library, this is really nice.

I have a question: how can we add unit testing for components using your hooks?

**Comment by iamyoki** [comment]
> Hi @iamyoki - thanks for your library, this is really nice.
> 
> I have a question: how can we add unit testing for components using your hooks?

Thanks for your attention, I didn't decide to do unit testing too soon until it became popular, so I'm working on an iterative design for v2.0 when the unit tests will be laid out.

The core concept won't change, but some API naming will be changed due to the naming conflict with the official hook of react18 , E.g.
`useTransition` -> `useTransAnimation`
`useSwitchTransition` -> `useSwitchAnimation`
`useListTransition` -> `useListAnimation`
(However I haven't decided it yet, suggestions are always welcome)
